"""A small, dependency-free toolkit for building and backtesting trading bots."""

from .backtest import (
    BacktestResult,
    EquityMetrics,
    MultiBacktestResult,
    run_backtest,
    run_multi_backtest,
)
from .bonds import modified_duration, par_bond_returns, total_return_index
from .broker import (
    Account,
    AlpacaBroker,
    Broker,
    BrokerError,
    BrokerOrder,
    BrokerPosition,
    Reconciliation,
    RiskLimitExceeded,
    RiskLimits,
    client_order_id,
    reconcile,
)
from .feed import BadBar, MergeResult, format_csv, merge, parse_csv, parse_stooq
from .indicators import ema, rsi, sma
from .live import Intent, NotSafeToTrade, check_freshness, check_reconciled, plan, plan_order
from .models import Candle, Fill, Order, Position, Side, Signal
from .paper import FrozenRule, JournalEntry, PaperRun, Report, years_to_detect
from .portfolio import InsufficientFunds, InsufficientPosition, Portfolio
from .prop import (
    INSTRUMENTS,
    PRESETS,
    DrawdownFloor,
    Instrument,
    PropAccount,
    RuinEstimate,
    breakeven_win_rate,
    contracts_for_risk,
    expectancy,
    max_risk_per_trade,
    ruin_probability,
)
from .significance import (
    SmoothnessCheck,
    autocorrelation,
    deflated_sharpe,
    expected_max_sharpe,
    moments,
    probabilistic_sharpe,
    smoothness,
)
from .sizing import FullInvestment, PositionSizer, VolatilityTarget
from .strategy import (
    BuyAndHold,
    PriceVsSma,
    SmaCrossover,
    Strategy,
    TimeSeriesMomentum,
)

__version__ = "0.1.0"

__all__ = [
    "Account",
    "AlpacaBroker",
    "BacktestResult",
    "BadBar",
    "Broker",
    "BrokerError",
    "BrokerOrder",
    "BrokerPosition",
    "BuyAndHold",
    "Candle",
    "DrawdownFloor",
    "EquityMetrics",
    "Fill",
    "FrozenRule",
    "FullInvestment",
    "INSTRUMENTS",
    "Instrument",
    "InsufficientFunds",
    "InsufficientPosition",
    "Intent",
    "JournalEntry",
    "MergeResult",
    "MultiBacktestResult",
    "NotSafeToTrade",
    "Order",
    "PRESETS",
    "PaperRun",
    "Portfolio",
    "Position",
    "PositionSizer",
    "PriceVsSma",
    "PropAccount",
    "Reconciliation",
    "Report",
    "RiskLimitExceeded",
    "RiskLimits",
    "RuinEstimate",
    "Side",
    "Signal",
    "SmaCrossover",
    "SmoothnessCheck",
    "Strategy",
    "TimeSeriesMomentum",
    "VolatilityTarget",
    "autocorrelation",
    "breakeven_win_rate",
    "check_freshness",
    "check_reconciled",
    "client_order_id",
    "contracts_for_risk",
    "deflated_sharpe",
    "ema",
    "expectancy",
    "expected_max_sharpe",
    "format_csv",
    "max_risk_per_trade",
    "merge",
    "modified_duration",
    "moments",
    "par_bond_returns",
    "parse_csv",
    "parse_stooq",
    "plan",
    "plan_order",
    "probabilistic_sharpe",
    "reconcile",
    "rsi",
    "ruin_probability",
    "run_backtest",
    "run_multi_backtest",
    "sma",
    "smoothness",
    "total_return_index",
    "years_to_detect",
]
